### ISSUE TITLE
Django2.0+、Python3.5合并报错AttributeError: module 'doctorai.robot' has no attribute 'check_signature'

### ISSUE THREAD

**Issue by devshilei** [offu/WeRoBot#297]
按照手册中与Django合并，出现如下报错信息：
Internal Server Error: /robot/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/werobot/contrib/django.py", line 27, in werobot_view
    if not robot.check_signature(
AttributeError: module 'xxx.robot' has no attribute 'check_signature'

**Comment by whtsky** [comment]
> Issue tracker 只用于反馈 bug 和 feature request。
