### ISSUE TITLE
突然100%故障了: Broken pipe

### ISSUE THREAD

**Issue by wqw547243068** [offu/WeRoBot#792]
本来好好的，从上周开始，公众号收不到消息，总是提示超时故障，后台log显示：管道破裂，是签名验证失败了吗？

```sh
127.0.0.1 - - [11/Feb/2023 17:53:55] "POST /?signature=39264461a3343f0d24e2b93a18f86db449b1834a&timestamp=1676109216&nonce=2115984383&openid=ocsr4jkBhvKMvwdYHXb5DnlYIuII HTTP/1.0" 200 349
Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib64/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by wqw547243068** [comment]
怀疑是请求超时5s触发
